### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by lx1** [Ardjlon/android_device_xiaomi_surya#1]
Hi Ardany,

this is not really an issue. I found your roms for the Poco X3 and they work great for me! Only, I found some releases on Androidfilehost and others on Sourceforge. Is there a unified public repo for them to find the last stable one, for what stable may mean. Anyway, thanks, great.

Luigi from Italy

**Comment by Ardjlon** [comment]
> Hi Ardany,
> 
> this is not really an issue. I found your roms for the Poco X3 and they work great for me! Only, I found some releases on Androidfilehost and others on Sourceforge. Is there a unified public repo for them to find the last stable one, for what stable may mean. Anyway, thanks, great.
> 
> Luigi from Italy

Hi bro, my main server is normally AFH, but a few days ago it started to fail, I don't know if it was just me or if it was general, so I couldn't get the build to that server, so I had to upload the latest build from EVOX to SF
